### ISSUE TITLE
Time value errors

### ISSUE THREAD

**Issue by Reforge-Mark** [cooler-SAI/WS548-v4#1]
When building, there are thousands of time value errors, even with latest visual studio 2015 x64 updates.
Time_Value.h(184): error C2238: unexpected token(s) preceding ';'
  Time_Value.inl(86): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
plenty of random errors like that. 
How did you manage to compile this source on x64?

**Comment by cooler-SAI** [comment]
Use only VS 2013
